### ISSUE TITLE
Not working in Ionic 4

### ISSUE THREAD

**Issue by vmundhra** [RodainaMohamed/ionic-rating#1]
Module not found: Error: Can't resolve 'ionic-angular' in '.../node_modules/ionic-rating/dist'

**Comment by MELAS007** [comment]
not working on ionic 4 ! please any advice!

**Comment by tavishaggarwal** [comment]
Any updates on this? When it can be fixed?

**Comment by austingrove** [comment]
Was able to get around this by changing file:
node_modules/ionic-rating/dist/ionic-rating.module.js

`import { IonicModule } from "ionic-angular";
`

to

`import { IonicModule } from "@ionic/angular";
`

**Comment by elega9t** [comment]
Can we get a release with the import { IonicModule } from "ionic-angular"; to import { IonicModule } from "@ionic/angular"; change please?

**Comment by elega9t** [comment]
`npm i ionic4-rating`

`import { IonicRatingModule } from 'ionic4-rating';`

works form me on ionic 4

**Comment by RodainaMohamed** [comment]
Hello guys, thanks for your patience as I didn't really have much time in the past period.

The library is now updated to support Ionic 4, check the changelog for the new updates.
