### ISSUE TITLE
Change icon Color

### ISSUE THREAD

**Issue by atologistkaushik** [RodainaMohamed/ionic-rating#4]
rating {
  ion-icon {
    color: red;
    &.filled {
      color: #ffb400;
    }
  }
}

add above to my .css but it is not going to work, can anyone please tell me how to change star icon color for normal icon and filled icon?

**Comment by elega9t** [comment]
`
rating {
  ion-icon {
      color: gray;
      &.filled {
        color: #fdbc2c !important;
      }
  }
}
`
works for me

**Comment by RodainaMohamed** [comment]
Please check the new version of the library that supports Ionic 4 and made it much easier to style the color of the stars using CSS Variables.
