### ISSUE TITLE
Rate change not firing action

### ISSUE THREAD

**Issue by jrodolforios** [RodainaMohamed/ionic-rating#9]
Hi! 

I'm using ionic rating component but rateChange is not firing de action. Can you help me with?

**Comment by Saqib92** [comment]
any update?

**Comment by Saqib92** [comment]
Blow code worked for me:

`<ion-rating [rate]="ratings" size="small" (rateChange)="youFunctionName(ratings, $event)"></ion-rating>`

i noticed `readonly` attribute causing this. Even if you are using `readonly="false"` it will not work. remove readonly and it will work.

**Comment by jrodolforios** [comment]
Yes! Worked for me! Thank you!

**Comment by Saqib92** [comment]
Close this issue. Thanks
